### PR TITLE
Mention how to update from old to new version…

### PR DESCRIPTION
**Pull request by slrslr**
process of updating should be simple

### CODE REVIEW

**Comment by maksis** [comment]
What's `airdcpp-webclient-old`? It's not mentioned in any other instructions. You can just replace the old files, there shouldn't be need to copy any config files or rename directories.

**Comment by slrslr** [comment]
> airdcpp-webclient-old
> You can just replace the old files

I usually backup old application for example, by renaming it to have "-2023-05-working" or "-old" suffix and let it be there for some time, so i can later return to working app or test if something worked in previous version.
If you think that this backup has no ground to be in tutorial, then exclude it and consider if rest of my addition can be left or just add your own mention how app update is done and where is a custom user configuration data.

I have already made a bash script to guide me through update, since i easily forget and researching each time how to properly update each app is really annoying. That is why i would appreciate to read about update in mine modified article and ideally also where are config data (not in $HOME/.config/ nor $HOME/.local/).

**Comment by maksis** [comment]
> just add your own mention how app update is done and where is a custom user configuration data.

I've added a few notes about updating the application in the docs, please see if the information provided is sufficient

**Comment by slrslr** [comment]
I think that it is better than it was, explains what needs to be done. Thank you

**Pull request closed without merging**
